export const manualHistoryRows = [
    {
        "Titulo":  "El Gato con Botas: El Útilmo Deseo",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.5",
        "Vargues":  "10",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "10",
        "Huguito":  ""
    },
    {
        "Titulo":  "Dragon Ball Super: Broly",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "10",
        "Javi":  "",
        "Huguito":  "9.75"
    },
    {
        "Titulo":  "Se7en",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "10",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "Interstellar",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "9.5",
        "Huguito":  "10"
    },
    {
        "Titulo":  "Pulp Fiction",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "10",
        "Vargues":  "10",
        "Meneses":  "9.5",
        "Jose":  "9.25",
        "Javi":  "",
        "Huguito":  "9.5"
    },
    {
        "Titulo":  "Malditos Bastardos",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.25",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "9.4",
        "Huguito":  ""
    },
    {
        "Titulo":  "Django Unchained",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "9",
        "Huguito":  ""
    },
    {
        "Titulo":  "Oppenheimer",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.5",
        "Vargues":  "8",
        "Meneses":  "9",
        "Jose":  "10",
        "Javi":  "",
        "Huguito":  "9.5"
    },
    {
        "Titulo":  "Top Gun: Maverick",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.25",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  "9"
    },
    {
        "Titulo":  "Inception",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  "9.75"
    },
    {
        "Titulo":  "Goodfellas",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.25",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "9",
        "Huguito":  ""
    },
    {
        "Titulo":  "Ratatouille",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9.5",
        "Vargues":  "10",
        "Meneses":  "",
        "Jose":  "8.25",
        "Javi":  "8.5",
        "Huguito":  ""
    },
    {
        "Titulo":  "Joker",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9",
        "Vargues":  "9",
        "Meneses":  "",
        "Jose":  "9.75",
        "Javi":  "9",
        "Huguito":  "8.5"
    },
    {
        "Titulo":  "No Country for Old Men",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9",
        "Vargues":  "9.25",
        "Meneses":  "",
        "Jose":  "9",
        "Javi":  "8.8",
        "Huguito":  ""
    },
    {
        "Titulo":  "Fight Club",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "10",
        "Javi":  "9",
        "Huguito":  "8"
    },
    {
        "Titulo":  "F1: The Movie",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9",
        "Vargues":  "9",
        "Meneses":  "",
        "Jose":  "8.5",
        "Javi":  "",
        "Huguito":  "9"
    },
    {
        "Titulo":  "Catch me if you can",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.75",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "9",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "El Lobo de Wall Street",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "9",
        "Vargues":  "9",
        "Meneses":  "",
        "Jose":  "9",
        "Javi":  "8.75",
        "Huguito":  "8"
    },
    {
        "Titulo":  "Ocean\u0027s Eleven",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "9",
        "Huguito":  ""
    },
    {
        "Titulo":  "Le Mans 66",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.75",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "Superbad",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "8.25",
        "Javi":  "10",
        "Huguito":  ""
    },
    {
        "Titulo":  "El Show de Truman",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.5",
        "Vargues":  "9",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "7.5",
        "Huguito":  "9"
    },
    {
        "Titulo":  "Shutter Island",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "8.5",
        "Huguito":  "9"
    },
    {
        "Titulo":  "Top Gun",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "The Man From Earth",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "Dragon Ball Super: Super Hero",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "8.25",
        "Javi":  "",
        "Huguito":  "8"
    },
    {
        "Titulo":  "Eyes Wide Shut",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "8.5",
        "Huguito":  ""
    },
    {
        "Titulo":  "Snatch",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8",
        "Vargues":  "8.5",
        "Meneses":  "",
        "Jose":  "8",
        "Javi":  "8.5",
        "Huguito":  ""
    },
    {
        "Titulo":  "Whiplash",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.25",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "10",
        "Javi":  "6.5",
        "Huguito":  ""
    },
    {
        "Titulo":  "Rush",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.25",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "Arrival",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.25",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "Nobody",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.25",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "8",
        "Javi":  "8.25",
        "Huguito":  ""
    },
    {
        "Titulo":  "Cars",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7.75",
        "Vargues":  "7.25",
        "Meneses":  "",
        "Jose":  "10",
        "Javi":  "8.75",
        "Huguito":  "7"
    },
    {
        "Titulo":  "John Wick 4",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.75",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "7.5",
        "Huguito":  ""
    },
    {
        "Titulo":  "Reservoir Dogs",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "8",
        "Huguito":  ""
    },
    {
        "Titulo":  "Cars 2",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7",
        "Vargues":  "6.5",
        "Meneses":  "",
        "Jose":  "9.5",
        "Javi":  "8.5",
        "Huguito":  "8.5"
    },
    {
        "Titulo":  "Conclave",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "8",
        "Javi":  "7.75",
        "Huguito":  ""
    },
    {
        "Titulo":  "One Battle After Another",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "8.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "7.5",
        "Javi":  "",
        "Huguito":  "7.5"
    },
    {
        "Titulo":  "El Camino",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7.5",
        "Vargues":  "8",
        "Meneses":  "",
        "Jose":  "7.75",
        "Javi":  "8",
        "Huguito":  ""
    },
    {
        "Titulo":  "The Big Short",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7.75",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "Ballerina",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "",
        "Huguito":  ""
    },
    {
        "Titulo":  "Once Upon a Time in Hollywood",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7.75",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "7",
        "Huguito":  ""
    },
    {
        "Titulo":  "American Psycho",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7",
        "Vargues":  "7",
        "Meneses":  "",
        "Jose":  "8",
        "Javi":  "7",
        "Huguito":  "7.5"
    },
    {
        "Titulo":  "Ted",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "7.25",
        "Javi":  "7.5",
        "Huguito":  ""
    },
    {
        "Titulo":  "Cars 3",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7",
        "Vargues":  "6.5",
        "Meneses":  "",
        "Jose":  "7",
        "Javi":  "7",
        "Huguito":  "6"
    },
    {
        "Titulo":  "Boss Nigger",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "6.5",
        "Vargues":  "",
        "Meneses":  "",
        "Jose":  "",
        "Javi":  "6.75",
        "Huguito":  ""
    },
    {
        "Titulo":  "Kung Fu Panda 1",
        "Año":  "",
        "Fecha":  "",
        "Isma":  "7.5",
        "Vargues":  "8",
        "Meneses":  "",
        "Jose":  "1",
        "Javi":  "10",
        "Huguito":  "1"
    }
] as const;
